# fly.toml file generated for Heart Game backend
# You can customize the app name after 'fly launch' or edit here.
app = "heart-catching-game"
primary_region = "iad"

[build]
# Use the Dockerfile in the repo

[env]
# Set your Vercel frontend URL after deploying frontend
# You can provide multiple origins separated by commas, e.g.:
# CLIENT_URL = "https://your-frontend.vercel.app, http://localhost:3001"
CLIENT_URL = "http://localhost:3001"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

# Enable TCP for WebSockets
[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
