name: Deploy backend to Fly.io

on:
  push:
    branches: [main]
    paths:
      - "server.js"
      - "package.json"
      - "Dockerfile"
      - "fly.toml"
      - "public/**"
      - ".github/workflows/fly-deploy.yml"

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      # Optional: ensure the app exists (no-op if already created)
      # - name: Ensure app exists
      #   run: |
      #     flyctl apps create $FLY_APP_NAME || true
      #   env:
      #     FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy (remote build)
        run: |
          # If you set FLY_APP_NAME secret, pass it. Otherwise fly.toml is used.
          if [ -n "${FLY_APP_NAME}" ]; then
            flyctl deploy --remote-only --app "$FLY_APP_NAME"
          else
            flyctl deploy --remote-only
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
