name: Deploy to Railway

on:
  push:
    branches: [main]
    paths:
      - "server.js"
      - "package.json"
      - "railway.json"
      - "public/**"
      - ".github/workflows/railway-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
